image: ghcr.io/eic/jug_dev:testing

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

vscode:
  extensions:
    - "ms-vscode.cpptools-extension-pack"
    - "redhat.vscode-yaml"
    - "redhat.vscode-xml"

tasks:
  - name: "Software Setup"
    init: |
      rm -rf /usr/local
      ln -sf /usr/._local/* /usr/local
    command: ddsim