name: linux-eic-shell

on: [push, pull_request]

jobs:
  build-and-check-overlap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        run: |
          # install ip6 repo
          git clone https://github.com/eic/ip6.git eic_ip6
          pushd eic_ip6
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX=install
          cmake --build build -- install
          export LD_LIBRARY_PATH=${PWD}/install/lib:${LD_LIBRARY_PATH}
          popd
          # install this repo
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX=install
          cmake --build build -- install
          export LD_LIBRARY_PATH=${PWD}/install/lib:${LD_LIBRARY_PATH}
          # link ip6 into install
          ln -sf ${PWD}/eic_ip6/install/share/ip6/ip6 install/share/ecce/ip6
          ls -al install/share/ecce
          ls -al install/share/ecce/ip6
          readlink install/share/ecce/ip6
          ls -al $(readlink install/share/ecce/ip6)
          find install/share/ecce
          # test
          checkOverlaps -c install/share/ecce/ecce.xml
